name: Test Iris ML App

on:
  pull_request:
    branches:
      - main
  # Optional: Allows manual testing
  workflow_dispatch: 

jobs:
  test:
    # Use a standard GitHub-hosted runner with Ubuntu
    runs-on: ubuntu-latest
    
    # ⚠️ Remove the 'container: image: node:20' block, 
    # as we need a clean Python environment setup.
    
    steps:
      - name: Checkout Code
        # Corrected action name and updated to a recent version
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        # This is the essential action for Python projects
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Match your local Python version

      - name: Install Dependencies & Pytest
        # Correct command to install packages from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Ensure pytest is available for running tests
          
      - name: Verify Model Exists (Crucial for ML App)
        # Checks if your pre-trained model is committed
        run: |
          if [ ! -f models/model_iris.pkl ]; then 
            echo "Error: models/model_iris.pkl is missing. Please commit the trained model."
            exit 1
          fi
          
      - name: Run Pytest
        # Executes the tests you placed in the 'tests/' directory
        run: pytest tests/